### ISSUE TITLE
ER Multiple registration forms with different field configurations

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/userswp#329]
To register different types of users, ask for different fields.

https://userswp.io/support/topic/initial-page-you-see-when-you-log-in/#post-6557

**Comment by pol76** [comment]
I would use the same approach WP uses for Menus.

See image attached:

![uwp-user-type](https://user-images.githubusercontent.com/25163253/99121562-39e31a80-25c2-11eb-827c-e934fa4e896c.JPG)

The same select would appear in the Register tab, however only the option to select the User Type would be available there. The add new user type would be available only on the account tab.

Let me know if there are any questions.

Thanks

**Comment by wpdev10** [comment]
Do we need a new addon for this or in the core? Instead of roles/user types can we create multiple forms and use the fields as needed in the forms? Let me know in detail so I can work on this. @pol76 @Stiofan

**Comment by Stiofan** [comment]
@pol76 lets discuss if this select is for our own purpose or actually selecting WP user roles.

**Comment by Stiofan** [comment]
@wpdev10 This is an internal account type and not a role select.  
A field should be added for role select, this field will only be visible to admins.

**Comment by wpdev10** [comment]
Few questions here:

- User role field has the selection of role while in the account form builder and if we add it to the default and other registration forms via form builder then it will assign the same role on both forms which is selected while creating the user role field in account builder.

- when we display the new registration form, it will show a login link below the form, and on click of it will open login form in popup but there will be a register link which will open the default registration form in the popup and not the new form from where we opened login link. What should we do here?

- Do we need to allow the user to select the default form which will display in the popup and on /register/ link? For page /register/ admin can change the form with shortcode or widget but not in a popup as we don't have any setting for that.

- What if one has a different Privacy policy or GDPR pages for the different forms to be accepted on registration? Right now we have a setting to choose the page for both in settings which will apply to the default form and other forms.

**Comment by Stiofan** [comment]
Clarifications:

- Paolo's image here https://user-images.githubusercontent.com/25163253/99121562-39e31a80-25c2-11eb-827c-e934fa4e896c.JPG should apply to all tabs "Account, Register, Profile tabs" so you can switch between user types.
- As above, each user type will have different settings for each tab.
- Register and profile tabs we already discussed.
- Account tab when a user type is selected then in the left sidebar at the top, we will show a box with "shared fields" that can be added to the form for that user (like below but in left side)
![create-usertype](https://user-images.githubusercontent.com/10433311/114896116-f3f7e000-9e07-11eb-8b52-f690cd2b8758.png)
- We will need to store the different field orders per user type, this could be done either by saving this in UWP option or add a column in the fields table for each user type.
- Shared fields either can't be edited once created or we add a warning that changing things will change for all types.
- For GetPaid, we will add a item select and an "Expire" on the account settings, below the "create new user type", this will let you select the GP item, and be able to set an action when this expires "downgrade to type x" or "Block till renewal"
- As above, this area might be the best place to set a user role also.
- For your point 2, lets just do it like that for now.
- for your point 3, yes.
- for your point 4, yes we need different settings.
