### ISSUE TITLE
ER - Add override for WP Welcome Email (email sent on new user registration when users register on the GD Add listing page)

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/userswp#348]
ER - Add override for WP Welcome Email (email sent on new user registration when users register on the GD Add listing page)
https://wpgeodirectory.com/support/topic/add-a-listing-3/#post-532770

I just thought you might want to consider adding an override to UWP in the future

this would be yet another great reason for people to install UWP

in the past we have actively decided not to override this with GD.
There are plugins on wp.org that will customize this email.

that would add another template designer to their site.

**Comment by alexrollin** [comment]
+20

**Comment by 1naveengiri** [comment]
https://secure.helpscout.net/conversation/1445333461/15881/

**Comment by 1naveengiri** [comment]
```
add_filter( 'wp_new_user_notification_email', 'wp_new_user_notification_email_custom_callback', 10, 3 );
function wp_new_user_notification_email_custom_callback( $wp_new_user_notification_email, $user, $blogname ){
	
		$key = get_password_reset_key( $user );
		if ( is_wp_error( $key ) ) {
			return;
		}


        $message  = sprintf( __( 'Username: %s' ), $user->user_login ) . "\r\n\r\n";
        $message .= __( 'Hey,  To set your password, visit the following address:' ) . "\r\n\r\n";
        $message .= network_site_url( "reset?action=rp&key=$key&login=" . rawurlencode( $user->user_login ), 'login' ) . "\r\n\r\n";


        $message .= uwp_get_login_page_url() . "\r\n";


        $wp_new_user_notification_email = array(
            'to'      => $user->user_email,
            /* translators: Login details notification email subject. %s: Site title. */
            'subject' => __( '[%s] Login Details' ),
            'message' => $message,
            'headers' => '',
        );
        return $wp_new_user_notification_email;
}
```

**Comment by 1naveengiri** [comment]
https://secure.helpscout.net/conversation/1498362453/18540?folderId=3817446

**Comment by wpdev10** [comment]
@1naveengiri It's already added in the 1.2.2.15 UWP core update. Check in the UsersWP->Emails->User emails->WP new user notification email. Let me know your thoughts!

**Comment by 1naveengiri** [comment]
Oh Sorry, How can I miss this. 

<img width="1633" alt="Screenshot 2021-04-29 at 12 59 19 PM" src="https://user-images.githubusercontent.com/24760592/116516053-bce6fb80-a8ea-11eb-87d2-597b15c7e153.png">
