### ISSUE TITLE
Additional fields on Form builder for displaying messages.

### ISSUE THREAD

**Issue by laranz** [AyeCode/userswp#406]
From a user.

As a suggestion for future updates, I would love to see copy fields added as an option (perhaps to replace a fieldset or in addition to). A heading field (bold headlines) and a description field (simple line of text without a form field) would be a great addition. This would also allow us to provide instructions to the users in the registration form and on the Account page.

**Comment by alexrollin** [comment]
In many form builders they call this an HTML Display field or a 'show' field - nice to have for GD, too.
