### ISSUE TITLE
WordPress database error after new update

### ISSUE THREAD

**Issue by laranz** [AyeCode/userswp#444]
WordPress database error: [Unknown column 'extras.form_id' in 'where clause']
SELECT fields.* FROM wp_uwp_form_fields fields JOIN wp_uwp_form_extras extras ON extras.site_htmlvar_name = fields.htmlvar_name WHERE fields.form_type = 'account' AND fields.is_active = '1' AND fields.for_admin_use != '1' AND fields.is_register_field = '1' AND extras.form_type = 'register' AND extras.form_id=1 ORDER BY extras.sort_order ASC

WordPress database error: [Unknown column 'extras.form_id' in 'where clause']
SELECT fields.* FROM wp_uwp_form_fields fields JOIN wp_uwp_form_extras extras ON extras.site_htmlvar_name = fields.htmlvar_name WHERE fields.form_type = 'account' AND fields.is_active = '1' AND fields.for_admin_use != '1' AND fields.is_register_field = '1' AND extras.form_type = 'register' AND extras.form_id=0 ORDER BY extras.sort_order ASC

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/208945/103778062-bee53000-5057-11eb-8f51-9a5a7fbe8ee6.png">

**Comment by wpdev10** [comment]
You will need to reactivate the plugin for this as this will be not an issue once we release an update as the DB will get changed on upgrade.
