### ISSUE TITLE
Replace jQuery(window).on("load" with jQuery(document).ready(

### ISSUE THREAD

**Issue by picocodes** [AyeCode/userswp#448]
No modal is loaded if a user clicks on the login link immediately after landing on a page. It only works after all scripts, styles and images are loaded, thanks to the following line.

```
jQuery(window).on("load", function() {
    uwp_init_auth_modal()
})
```

Is there a specific reason as to why we're using window.onload? If not, we can replace the line with:-

```
$(function() { uwp_init_auth_modal()});
```

Which fires after the document is ready, and not after everything is loaded.

The first code might also fail to fire if some resources fail to load, though I've not tested that.

**Comment by wpdev10** [comment]
It doesn't work when we put on the same as you suggested. We can put it on the document ready call or on window load call. Because it depends on the Bootstrap library as well.

**Comment by picocodes** [comment]
How about adding the aui handles as dependancies when registering UWP scripts?

**Comment by wpdev10** [comment]
AUI register script based on its settings in the backend and I don't think we should use the same setting check for registering our script. Also, we have a legacy layout support setting to allow users to use their own design and layouts. Is there anything critical issue if we keep this on document load?
