### ISSUE TITLE
Conflict check

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/userswp#451]
https://wordpress.org/support/topic/users-wp-events-calendar-conflict/

**Comment by wpdev10** [comment]
This is due to Bootstrap loading via AUI. Changing the setting in Load JS solved this for the customer.

**Comment by Stiofan** [comment]
Can you be more specific? Who's setting, their's or ours, load what JS?

**Comment by wpdev10** [comment]
I could not regenerate the issue as the issues might be on the customer's site only and also we are now loading AUI on specific pages in the backend so no more chances of conflicts.
