### ISSUE TITLE
Admin always redirect to wp-admin

### ISSUE THREAD

**Issue by pol76** [AyeCode/userswp#459]
Hi,

the Login Redirect Page shouldn't redirect to what is set in the Login Redirect Page.

It should always redirect to the wp-admin dashboard.

Please change that option ASAP.

Thanks,

**Comment by wpdev10** [comment]
@pol76 Do you mean for admin users? Need more detail.

**Comment by Stiofan** [comment]
Yes this is for admin users, i also find this annoying.
