### ISSUE TITLE
UWP compatible with at least 1 2FA plugin

### ISSUE THREAD

**Issue by wpdev10** [AyeCode/userswp#461]
https://secure.helpscout.net/conversation/1455264256/16437?folderId=3817469

**Comment by wpdev10** [comment]
I have checked with the https://wordpress.org/plugins/wp-2fa/ plugin and it works for the login page but not for the login popup because in the login popup WP2FA plugin exits by outputting the 2FA input form which breaks our AJAX call.

**Comment by Stiofan** [comment]
I have checked that plugin and we should be able to make it compatable with our ajax login.

1. Disable their hook output their html on ajax login.
2. Make our own form from their form inputs and from their functions and submit it back via ajax and authenicate it via their functions.
