### ISSUE TITLE
User Role feature doesn't appear to be working

### ISSUE THREAD

**Issue by pol76** [AyeCode/userswp#470]
Hi,

unless I'm missing something when the User Role field is added to the account form, it doesn't do anything.

When added to the registration form, it prevents registration because validation always comes up with this alert:  

**Error: User Role cannot be empty.**

Please explain to me how this works? Has it been tested?  

Thanks,

**Comment by wpdev10** [comment]
I have excluded it from checking for required field conditions when Is required enabled for the custom field. Otherwise, functionality working fine.

**Comment by pol76** [comment]
Ok thanks, please see: https://github.com/AyeCode/geodirectory/issues/1665
