### ISSUE TITLE
Reproduce bug: duplicate fields in registration tab

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/userswp#472]
<img width="1680" alt="Screenshot 2021-03-25 at 6 54 47 PM" src="https://user-images.githubusercontent.com/24760592/112480520-216ae400-8d9c-11eb-8f61-b3a68496bc30.png">
<img width="1504" alt="Screenshot 2021-03-25 at 6 58 57 PM" src="https://user-images.githubusercontent.com/24760592/112480625-39dafe80-8d9c-11eb-99a4-c3e7d2441c3c.png">

**Comment by 1naveengiri** [comment]
https://secure.helpscout.net/conversation/1462540655/16775?folderId=3817467

**Comment by 1naveengiri** [comment]
I tried several cases, Unable to reproduce this issue. 
I am still keeping this active, just in case it reported by any other customer.

**Comment by 1naveengiri** [comment]
I can't reproduce it also no other customer reported it. 

I am closing it here.

**Comment by jordane2086** [comment]
I am having this same issue. Anyone fix this yet?

**Comment by wpdev10** [comment]
@jordane2086 Please try to do a complete uninstall of the plugin and then install it again. To complete uninstall you should first enable the setting at UsersWP->Uninstall->Remove Data on Uninstall? and if you see more options there which should be because you might have enabled addons then you should do it for all addons and then deactivate and delete the addons first and after that deactivate and delete the UsersWP core plugin. This will delete everything from the database created or added by UsersWP.

**Comment by jordane2086** [comment]
That worked. Thank you for the help!

Warm Regards,

Jordan Erickson

Creative Director, Conceptualized Design
www.ConceptualizedDesign.com <https://www.conceptualizeddesign.com/> |
+1.785.236.1777 <+17852361777>
*Schedule a Consult <https://calendly.com/conceptualized-design/>*

Need to submit a Support, Update, or Change Request? Click Here
<https://clients.conceptualizeddesign.com/support/>, or email us at:
***@***.***
Who's powering your digital marketing? Learn about Us.
<https://conceptualizeddesign.com/>
If you need to sign up for a web hosting plan, please Visit Our Website and
Sign Up
<https://www.conceptualizeddesign.com/digital-web-services/website-care-plan/>
.
Want to tell us how we are doing? Leave us a review on our Facebook
<https://www.facebook.com/pg/conceptualizeddesign/reviews/> and Google
<https://g.page/conceptualizeddesign/review?gm> pages.

<https://www.conceptualizeddesign.com/>

<https://www.facebook.com/conceptualizeddesign/>
<https://www.linkedin.com/company/3623365/>

Notice: This e-mail is covered under the Electronic Communications Privacy
Act, 18 USC 2510-2521, and is legally privileged. The information contained
in this e-mail is intended only for use of the individual or entity named
above. If the reader of this message is not the intended recipient, you are
hereby notified that any dissemination, distribution or copying of this
communication is strictly prohibited. If you have received this
communication in error, please immediately notify us by telephone at the
above number and permanently delete all copies of the original message.
