### ISSUE TITLE
User Enumeration attack on lost password screen

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/userswp#477]
https://secure.helpscout.net/conversation/1470273983/17198?folderId=3817446

**Comment by wpdev10** [comment]
We had this before but later we changed it to the actual message instead of always showing a success message due to requests from the customers on support tickets. Should we revert back? @Stiofan

**Comment by Stiofan** [comment]
If its an easy addition then lets add a filter for it but keep it the way it is now by default (same as WP does)

**Comment by wpdev10** [comment]
I have checked in the WP default lost password form and it also has the error message instead of always showing a success message. I have also added the filter to allow changing it. Also checked with the WC and it's also showing an error message.

**Comment by Stiofan** [comment]
Please provide example usage of the filter and i will ask Sufyan to add a doc.

**Comment by wpdev10** [comment]
add_filter('uwp_forgot_error_message', 'uwp_forgot_error_message_cb', 10, 1);
function uwp_forgot_error_message_cb(){
    return array(
	    'type'    => 'success',
	    'content' => __( 'A reset link has been sent to your email address to reset the password.', 'userswp' )
    );
}
