### ISSUE TITLE
common hook to change admin email address for admin specific emails

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/userswp#483]
https://secure.helpscout.net/conversation/1471192989/17234?folderId=3817446

**Comment by 1naveengiri** [comment]
@wpdev10 do you think we can face an issue with this common filter? 
https://github.com/AyeCode/userswp/pull/484/files

**Comment by wpdev10** [comment]
There is already a filter "uwp_send_email_to" which can be used to change the email address to whom the email is sent. It can be a single value or an array of multiple emails so no need to provide another filter for this.
