### ISSUE TITLE
Warning after install userwp without the default recommended plugins.

### ISSUE THREAD

**Issue by laranz** [AyeCode/userswp#485]
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/208945/114127878-c21edf00-9918-11eb-8050-f44ad1d949e4.png">

**Comment by wpdev10** [comment]
@laranz Can you write steps to reproduce or have a video with the issue to get more ideas and make sure all the plugins are upto date?

**Comment by laranz** [comment]
1. I Installed Query Monitor & Debug Bar.
2. Installed UsersWP on a fresh install,
3. Follow all the steps, and skip the plugin installation step,
4. and visit the Dashboard after all finished,
5. and we get this error.

@wpdev10

**Comment by wpdev10** [comment]
@laranz Can you check now with the latest UsersWP from git if the issue is solved or not?
