### ISSUE TITLE
"Field key should be a unique name." error after adding first element and save.

### ISSUE THREAD

**Issue by laranz** [AyeCode/userswp#488]
![image](https://user-images.githubusercontent.com/208945/114525927-2537ab00-9c64-11eb-8417-9ee35298f057.png)

1. Create a new form and give it a name.
2. Add a element, I am adding username here.
3. Click save on the Username element and it gives this error.

**Comment by laranz** [comment]
@wpdev10  maybe this is the cause, it happens at random times, sometimes it happens, sometimes not.

![image](https://user-images.githubusercontent.com/208945/114579012-14eef280-9c9b-11eb-8abf-28ff200a3003.png)

**Comment by wpdev10** [comment]
@laranz I have removed the save button so the issue is solved :) There are no options in the register fields so no need to have a save button there.

**Comment by laranz** [comment]
@wpdev10 removed save button only on "Username"?

![image](https://user-images.githubusercontent.com/208945/114751676-11c73580-9d73-11eb-803d-643232baa3cd.png)

**Comment by wpdev10** [comment]
We hide it for all fields as it will be saved by default when we add a field to the selected field.
