### ISSUE TITLE
New form not displaying.

### ISSUE THREAD

**Issue by laranz** [AyeCode/userswp#493]
1. Create a new form,
2. Copy the shortcode.
[uwp_register id="2" title="Google"]
3. Put that in a page ( I am using Classic Editor, because Gutenberg displays some error on #490 )
4. But the page display empty https://ppldb.com/uwp/new-form/
5. Should this only work if I change the register page in UWP > Pages? Did that, but it still displays the default register form.

**Comment by wpdev10** [comment]
@laranz Are you looking from the non-logged-in user or from the logged-in user? I see a form if I visit the link without login.

**Comment by laranz** [comment]
@wpdev10 now the form displays, but if we change the register page here: https://ppldb.com/uwp/wp-admin/admin.php?page=userswp it didn't display on this page https://ppldb.com/uwp/register/

**Comment by wpdev10** [comment]
You need to check the URL. You are accessing the default register page from https://ppldb.com/uwp/register/ as if you assign the new page from setting then it will have a different URL so you will need to visit that page URL. We have setting to identify what is registration page and we can use it where we use/change the registration link.
