### ISSUE TITLE
New Registration Email.

### ISSUE THREAD

**Issue by laranz** [AyeCode/userswp#498]
Register Form:

![image](https://user-images.githubusercontent.com/208945/114763029-00385a80-9d80-11eb-8d9e-a0cad15e6f05.png)

Email:

![image](https://user-images.githubusercontent.com/208945/114763094-10503a00-9d80-11eb-8ec6-f803940e91ed.png)

It contains the first name and last name as empty, it is not included in the register form.. is this by design?

**Comment by wpdev10** [comment]
If you don't have a first name and last name field in the form how you will receive it in the email? So for that, you will have to change the email template and remove the first name and last name field from email content in our settings for the "New account registration" admin email.
