### ISSUE TITLE
Users list style issue for user image

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/userswp#509]
https://demos.ayecode.io/supreme-directory/users/

.uwp-users-loop .tofront img{ 
max-width: 100%;
}

**Comment by 1naveengiri** [comment]
https://demos.ayecode.io/supreme-directory/users

**Comment by wpdev10** [comment]
This depends on the theme. Generally img has default CSS max-width: 100%; but our theme doesn't have it. But I have added "mw-100" to fix this independent of the theme.
