### ISSUE TITLE
UsersWP Membership addon

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/userswp#510]
We can create an addon that allows defining membership plans. 
we can also use GetPaid to enable paid options https://github.com/AyeCode/userswp/issues/429

the plugin will also provide an option to enable/disable features of UsersWP addons for specific membership types.
https://secure.helpscout.net/conversation/1492479884/18226?folderId=3817446

**Comment by wpdev10** [comment]
https://secure.helpscout.net/conversation/1427413219/14962?folderId=3817469

**Comment by pol76** [comment]
see https://github.com/AyeCode/uwp-membership/issues/1
