### ISSUE TITLE
metadata support for SEO plugins on user profile page

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/userswp#514]
https://secure.helpscout.net/conversation/1502545219/18732?folderId=3817467

**Comment by wpdev10** [comment]
I replied to the ticket with a filter and as SEOPress is not the most used plugin we should wait if more people are using it before adding support in the core UWP plugin. cc @Stiofan

**Comment by wpdev10** [comment]
Here is the filter provided as a solution:
add_action('seopress_titles_title', array(new UsersWP_Seo(),'get_title'));

**Comment by Stiofan** [comment]
lets add a compatibility class like GD has and auto add this there?
