### ISSUE TITLE
Required Message is wrong for GDPR and TOS checkboxes.

### ISSUE THREAD

**Issue by laranz** [AyeCode/userswp#518]
![image](https://user-images.githubusercontent.com/208945/117692823-05e85b00-b1db-11eb-8e54-41a2b017b8ba.png)

**Comment by wpdev10** [comment]
That is a browser message as we use the "required" attribute in the tag and our message set in the custom field option will display when someone submits the form without marking the checkbox checked and "required" is not supported by the browser.

**Comment by Stiofan** [comment]
The custom message should be able to show if we are uign HTML required
