### ISSUE TITLE
Delete Button not showing after adding the Field

### ISSUE THREAD

**Issue by laranz** [AyeCode/userswp#519]
![image](https://user-images.githubusercontent.com/208945/117695899-5a410a00-b1de-11eb-877b-86588f8248b8.png)

It only shows after we "Save" the field.

Expected Result: Delete Button should show after adding the field itself.

**Comment by wpdev10** [comment]
The field is actually added to DB when saved. Not a bug.

**Comment by Stiofan** [comment]
If i add the field and then decide I don't want it then I have no way to remove it, that's bad UX, it should still have a remove button that just removes the container if not saved. (like GD does)

**Comment by laranz** [comment]
Two bug on this.

1. When we add fields continuously, randomly first or second added field is opening, not the newly added field. ( When I add the 4th Radio field, see the first added Text field is open )

2. When we start deleting the field, it delete from the top not the field that I click "Delete" ( When I delete the Select field it deletes the Text Area )

Screenshot:
https://screencast-o-matic.com/watch/crh264VfuS3

**Comment by wpdev10** [comment]
The issue is the new field key is the same for all the fields till not saved. The same issue happens with the GD form builder as well. I am looking into the solution.
