### ISSUE TITLE
Adding Description for "GDPR Policy Page" and "Terms and Condition"

### ISSUE THREAD

**Issue by laranz** [AyeCode/userswp#521]
![image](https://user-images.githubusercontent.com/208945/117697274-eb64b080-b1df-11eb-840f-462400b31b26.png)

to show the TOS and GDPR on the registration forms we need to add the field "GDPR Policy Page" and "Terms and Condition", is there any option to add a description to these elements under "Form Options" so that the user can know?

**Comment by wpdev10** [comment]
Do you mean to change the description displayed on the form on the front end? For that one can use the following in the field description where %%link_start%% and %%link_end%% will add the link to the policy page set in setting.

Please accept our %%link_start%% GDPR Policy %%link_end%%
