### ISSUE TITLE
Gender Dropdown is big on Backend profile page

### ISSUE THREAD

**Issue by laranz** [AyeCode/userswp#530]
![image](https://user-images.githubusercontent.com/208945/117806181-92e0f200-b277-11eb-91ad-71f713f5efd4.png)

1. Add Gender to the "Registration" or "Accounts" Tab.
2. Add details for Gender,
3. Then view it in the backend.
4. Dashboard -> Users -> Profile. or visit the correct User.

**Comment by wpdev10** [comment]
This is because AUI is adding width:100% for all select2 fields not sure why. @Stiofan

**Comment by Stiofan** [comment]
You should be able to override this with classes?

**Comment by wpdev10** [comment]
I have added a w-50 class to show all the fields in 50% width in the profile fields in the backend.
