### ISSUE TITLE
No Remove button for second "Email" field.

### ISSUE THREAD

**Issue by laranz** [AyeCode/userswp#537]
![image](https://user-images.githubusercontent.com/208945/118262571-b18ef500-b4d2-11eb-8705-4bbf8e0ac619.png)

**Comment by wpdev10** [comment]
Email is the required field in the registration form so we don't give a remove button for email.

**Comment by laranz** [comment]
Now the email field is removable, if that is required for registration we shouldn't.

1. If we add a second email field ( by accident! ), then we should remove only the second email field.

**Comment by wpdev10** [comment]
I have displayed the remove link for all the fields now. If there are no fields in the form then it will not show fields in the form in the frontend and the admin will require to add fields to the form builder.
