### ISSUE TITLE
UWP fields label is not appearing on registration form over popup

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/userswp#546]
the field label is not appearing on the registration form popup. 

<img width="1185" alt="Screenshot 2021-05-24 at 1 58 41 PM" src="https://user-images.githubusercontent.com/24760592/119319642-54483000-bc98-11eb-9fb9-4c3f9003868b.png">

although it is appearing on registration page 
<img width="1176" alt="Screenshot 2021-05-24 at 1 59 27 PM" src="https://user-images.githubusercontent.com/24760592/119319677-5e6a2e80-bc98-11eb-920c-3a41a33176a9.png">

**Comment by Stiofan** [comment]
@wpdev10 i think we need to change this line https://github.com/AyeCode/userswp/blob/master/includes/class-forms.php#L3086
to something like: 
`					'label'           => is_admin() && !wp_doing_ajax() ? '' : $site_title . $required,
`
