### ISSUE TITLE
Multiform bugscrub

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/userswp#548]
- [x] If we have role option in form options can we remove the field?
- [x] Option to add a field to reg form should be moved from advanced to normal view.

**Comment by pol76** [comment]
I update the plugin with latest version and I still see both the Role option and the Role field?

**Comment by pol76** [comment]
Option to add a field to reg form has not been moved from advanced to normal view?

**Comment by pol76** [comment]
Fix UI of custom fields on left sidebar:

from this:
**Not Good**
![h3-custom-fields-no-good](https://user-images.githubusercontent.com/25163253/119570301-8aa7ad00-bd75-11eb-83c1-181075889de1.JPG)

to this:
**Good**
![h3-custom-fields-good](https://user-images.githubusercontent.com/25163253/119570321-92675180-bd75-11eb-8a72-23f69eaafebe.JPG)

You can do it by editing CSS as follow (addition in bold)

#uwp_form_builder_container .uwp-side-sortables h3 {
    font-size: 15px;
    font-weight: normal;
    line-height: 1;
    padding: 8px 10px;
    margin: 0;
    border-bottom: 1px #DFDFDF solid;
    text-shadow: 0 1px 0 #ffffff;
    **border-top: 1px solid #DFDFDF;** 
    }
    
    #uwp_form_builder_container .uwp-side-sortables .inside {
    position: relative;
    margin: 10px 0;
    line-height: 1.4em;
    padding: 0 12px 0 10px;
    **overflow: hidden;**
}

Thanks

**Comment by pol76** [comment]
Other than the UX/UI issue above everything looks good to me...

**Comment by wpdev10** [comment]
Applied the changes.
