### ISSUE TITLE
Warning after a fresh userswp install from wp.org.

### ISSUE THREAD

**Issue by laranz** [AyeCode/userswp#552]
![image](https://user-images.githubusercontent.com/208945/119806358-c2426080-beff-11eb-96ce-12ba7e9609e7.png)

    wp-content/plugins/userswp/vendor/ayecode/wp-super-duper/wp-super-duper.php:1740
    WP_Super_Duper->block()
    wp-content/plugins/userswp/vendor/ayecode/wp-super-duper/wp-super-duper.php:1500
    WP_Super_Duper->register_block()
    wp-includes/class-wp-hook.php:292
    do_action('admin_enqueue_scripts')
    wp-admin/admin-header.php:102

**Comment by wpdev10** [comment]
This must be solved as I have added 'default'     => '', an argument where it was missing as it was causing an error. There needs a 'default' argument in each option while registering widget for the SD class.
