### ISSUE TITLE
Inputs for the doc site.

### ISSUE THREAD

**Issue by wpdev10** [AyeCode/userswp#563]
**Corrections:**
https://docs.userswp.io/article/357-requirements
[Remove the last paragraph in hosting from this doc.]

https://docs.userswp.io/article/156-installing-userswp
[Add video from https://userswp.io/docs/getting-started/basic-installation/ on new doc site somewhere.]

https://docs.userswp.io/article/410-using-userswp-on-wp-multisite
[Should be copied from the old doc https://userswp.io/docs/getting-started/network-activation/.]

https://docs.userswp.io/category/337-explore-settings
[Can we arrange links based on the settings order in the backend?]

https://docs.userswp.io/article/408-settings-overview-for-userswp-general-register
[Remove Registration Action, Register TOS Page, GDPR Policy Page as we will have this option per account form builder after multiple registrations forms functionality introduced in the last update. Also, there will be more options displayed when you select Force Redirect or auto-approve in registration action.]

Core Widgets
[Move it to Getting Started section]

https://docs.userswp.io/article/524-settings-overview-for-userswp-addons-activity
https://docs.userswp.io/article/525-activity-setup-guide
[If you activate all addons you will see more options in the setting. Please include them all here.]

**New docs:**

Notification Addon:
- Doc for popup notification

**New docs from old docs content(Mostly copy-paste):**

To be continued...

**Comment by sufyanism** [comment]
Fixed everything except **Core Widgets [Move it to Getting Started section]**

**Comment by wpdev10** [comment]
Please keep this open for more time as I will be adding more points when I will get time.
