### ISSUE TITLE
Hide account tabs that are not in use

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/userswp#586]
Member request to hide notifications tab that is blank

https://secure.helpscout.net/conversation/1592868034/22847?folderId=3803506

**Comment by wpdev10** [comment]
Duplicate issue #565

**Comment by wpdev10** [comment]
We can send doc link to hide them using filter: https://docs.userswp.io/article/578-how-to-remove-notifications-and-privacy-from-account-options
