### ISSUE TITLE
Redirect option for registration form shouldn't be a Registration Action:

### ISSUE THREAD

**Issue by pol76** [AyeCode/userswp#593]
Registration Action option should only include things related to registration status like auto-approved, auto-login or require email activation. Redirect should be an option of its own. 

We should also improve user redirect after login and make it role-based.

We can take inspiration from this plugin: https://wordpress.org/plugins/role-based-redirect/

Thanks,

**Comment by Stiofan** [comment]
only show redirect option if "Auto approve + Auto Login " is selected.

**Comment by pol76** [comment]
![Capture](https://user-images.githubusercontent.com/25163253/130832195-fec756a2-5524-47f6-a3df-2d5aa2551d06.JPG)

Add login redirect for each form and make sure the role selected for one form, is not available for selection on other forms (each role can only be used by one form...)
