### ISSUE TITLE
Fields repeating

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/userswp#612]
I don't have any steps to reproduce this issue but the customer reported it.  

<img width="1680" alt="Screenshot 2021-10-30 at 10 24 53 PM" src="https://user-images.githubusercontent.com/24760592/139542117-42a58995-66fa-48bb-a77a-ffb19825a3af.png">

**Comment by wpdev10** [comment]
This can be due to multiple installations without complete uninstall or not properly installing the plugin.
