### ISSUE TITLE
UWP > User Avatar shortcode by default loading thumbnail image and blur on size increase

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/userswp#614]
https://secure.helpscout.net/conversation/1679443994/25931?folderId=3812058

**Comment by wpdev10** [comment]
@1naveengiri That is not an issue from UWP. We load an avatar image of 150x150 and the customer is trying to load it into a 300x300 container which will obviously stretch the image. Assign the ticket to me to check how he is loading an avatar and I can help him fix it.

**Comment by 1naveengiri** [comment]
@wpdev10 ideally this setting should help in changing image size but it is not.

<img width="1251" alt="Screenshot 2021-11-01 at 6 33 09 PM" src="https://user-images.githubusercontent.com/24760592/139675807-cc7bc45f-40c7-46a0-ad6c-8416fda85531.png">

**Comment by wpdev10** [comment]
@1naveengiri It should work or let me know the test site URL where I can see the issue to fix.

**Comment by 1naveengiri** [comment]
I am checking it locally. you can check it on your local, I have assigned the ticket to you.

**Comment by wpdev10** [comment]
@1naveengiri It works fine for me local as well. If you can regenerate the issue on the server on any test site then I can take a look into it.

**Comment by wpdev10** [comment]
Looks like a site-specific or theme-specific issue. Reopen if there are any steps to regenerate it.
