### ISSUE TITLE
First Name (A-Z) not shown on frontend.

### ISSUE THREAD

**Issue by laranz** [AyeCode/userswp#628]
1. Delete the userswp plugin from the folders in an old installation.
2. Download latest from userswp github, and paste in the old installation plugins folder.

# Backend.
![image](https://user-images.githubusercontent.com/208945/148115416-1471a344-887a-46d6-b5d3-ba41df4cfd69.png)

# Frontend.
![image](https://user-images.githubusercontent.com/208945/148115378-c0238593-a0ea-461b-b77d-b225222a1569.png)

**Comment by wpdev10** [comment]
For our new functionality, you need to completely uninstall and install the plugin again as we run the upgrade function on version change.

**Comment by laranz** [comment]
Fixed on latest version, installed directly from github to a freshly installed wp installation.
