### ISSUE TITLE
Ajax error when trying to save the "Sorting Options" on an old installation.

### ISSUE THREAD

**Issue by laranz** [AyeCode/userswp#629]
1. Try to make the First name (A-Z) as the default sort.
2. Click Save, and it gives some ajax warning.
3. But it saves the option.

![image](https://user-images.githubusercontent.com/208945/148115713-6f694127-6673-4238-9d73-75b4b00c4145.png)

**Comment by laranz** [comment]
Another scenario, adding email from the default field to sorting, and trying to save..

![image](https://user-images.githubusercontent.com/208945/148116022-37678c10-f8a3-43d2-9a87-eb566be12e6b.png)

**Comment by wpdev10** [comment]
Try in old version of UWP on wp.org and then fresh WordPress version and let me know if this happens or not.

**Comment by laranz** [comment]
This isn't happening on fresh wp installation. ( It does happen when we try install uwp on wp.org and then update the plugin via git )

**Comment by laranz** [comment]
Happening on saving a custom element. ( Fresh install on wp, from this repo ) @wpdev10 

![image](https://user-images.githubusercontent.com/208945/148296482-fd9f5a09-0d4a-4eb6-8093-054098017f25.png)

**Comment by wpdev10** [comment]
It should be fixed now. Let me know the video if not and check in both fresh install and old install.

**Comment by laranz** [comment]
This is happening only when I am having "Query Monitor" plugin, can you check by installing the plugin?  @wpdev10

**Comment by wpdev10** [comment]
I don't see the same issue now so I am closing this for now.
