### ISSUE TITLE
Error while adding two same elements.

### ISSUE THREAD

**Issue by laranz** [AyeCode/userswp#630]
( Old installation, new plugin )
1. Adding email to the sorting options.
2. Adding the email element and choose ascending and save.
3. Now adding the email element again for the descending options, choose descending and changed the title and hit save,
4. It shows this error popup,

![image](https://user-images.githubusercontent.com/208945/148119409-c6acd7c6-dfaf-4324-a225-623ed9d1a0c3.png)

**Comment by wpdev10** [comment]
Fixed.
