### ISSUE TITLE
Review without rating is not visible users profile

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/userswp#632]
here we have a check to exclude CPT if the rating is disabled.
https://github.com/AyeCode/userswp/blob/master/includes/libraries/class-geodirectory-plugin.php#L764

but if **Disable review stars without disabling comments.** is turned on. 
it does not show the CPT in the profile review tab.  

and hence it sounds to be an issue for the customer
https://secure.helpscout.net/conversation/1743952417/27868?folderId=3812058

**Comment by 1naveengiri** [comment]
In my opinion, we should remove that check. 

Even though the review is enabled without rating. it is still a review. 
it should still be visible in the profile review tab.

**Comment by wpdev10** [comment]
We have added a filter 'uwp_profile_gd_show_all_reviews' to allow displaying reviews without ratings.
