### ISSUE TITLE
Can't modifying email in account page

### ISSUE THREAD

**Issue by nicleg** [AyeCode/userswp#669]
Hi 
thank's for this plugin which looks to works very well.

I'm facing an issue : on the account front-end page, I can modify the email in the field (id="email" class=" uwp_textfield ") and once the page saved it appears changed in the page, ... but not in the admin, and if you try to reload the account page once saved, the old value is back.

Is there a WP setting to prevent users to change their mail perhaps ? or in the usersWP plugin ?

Thanks for your reply.
Nicolas

**Comment by nicleg** [comment]
Sorry, I havent' noticed : Fixes here https://github.com/AyeCode/userswp/issues/619

**Comment by wpdev10** [comment]
@nicleg 
You will need to confirm the new email via the verification link received in the inbox to apply the new email address. This is similar to changing the admin email address from settings in WordPress.
