### ISSUE TITLE
Add option to require strong password

### ISSUE THREAD

**Issue by Stiofan** [AyeCode/userswp#680]
Add option to require strong or medium password
https://wordpress.org/support/topic/strong-password-enforce/

**Comment by wpdev10** [comment]
We already have minimum and maximum password length setting in UsersWP->General->Register->Show Advanced and for strong password check, we can add a new setting there if enabled we force users to use a strong password on registration.

**Comment by Stiofan** [comment]
i know about those.  We need a select option, "Minimum password strength" None, Medium, Strong
