### ISSUE TITLE
user profile privacy does not work

### ISSUE THREAD

**Issue by alexrollin** [AyeCode/userswp#691]
https://secure.helpscout.net/conversation/2112741371/38945?folderId=3817446

![image](https://user-images.githubusercontent.com/114659/210281489-37f3f2cf-7451-4241-a6ac-935dee8de9e0.png)
**
**
This option does not seem to work, and the user profile card is still shown in the users page listing.

**Comment by sachyya** [comment]
I checked on my setup and could not replicate the issue.
