### ISSUE TITLE
Cropping of profile picture (avatar) in backend not working

### ISSUE THREAD

**Issue by pol76** [AyeCode/userswp#709]
Cropping of the profile picture (avatar) in the backend is not working. Please test and fix. I haven't tested the banner, please check that too.

**Comment by wpdev10** [comment]
@pol76 Can you let me know where it's not working? I need to check if Bootstrap is loaded there or not and if loaded then is there any conflicts or not. It's working fine for me on my local and test site.

**Comment by pol76** [comment]
Enabling Bootstrap 5 solved the problem. It should work with BS4 too, but unless anyone else complains we can ignore for now. Thanks

**Comment by wpdev10** [comment]
@pol76 FYI...It works for me on both BS4 and BS5. If needed troubleshooting then share with me the site URL where I can regenerate the issue.
