### ISSUE TITLE
Profile Page Not Found

### ISSUE THREAD

**Issue by leilanisouza** [AyeCode/userswp#729]
The Account and Users pages work fine, but the Profile page shows not found.
![account](https://github.com/AyeCode/userswp/assets/152564189/62e0f13d-77e0-4e5c-b3d2-83231cce5fa3)
![users](https://github.com/AyeCode/userswp/assets/152564189/76634f18-7b93-4cbe-8cec-e0c2a19b5286)
![profile](https://github.com/AyeCode/userswp/assets/152564189/d93ad318-d326-48ba-a417-da89f24d3487)

**Comment by pol76** [comment]
hi, please create a support ticket here: https://userswp.io/support/
You'll get a faster response...
Thanks
