### ISSUE TITLE
Clicking the profile link when logged out should redirect to login page.

### ISSUE THREAD

**Issue by pol76** [AyeCode/userswp#732]
https://wordpress.org/support/topic/clicking-profile-page-when-logged-out-doesnt-redirect-to-login-page/#post-17432114

**Comment by wpdev10** [comment]
Profile pages are public and doesn’t require login to access it. We already have option to have profile tabs visibility based on login status but page will be public so anyone can see others profiles. Account pages are restricted to logged in users.
