### ISSUE TITLE
Action failed. Please refresh the page and retry.

### ISSUE THREAD

**Issue by bluenor** [AyeCode/userswp#733]
Hi, when I try to access the main plugin panel: 

wp-admin/admin.php?page=userswp

unfortunately I get this error:

#: admin/class-admin-setup-wizard.php:51 admin/settings/class-settings.php:76
msgid "Action failed. Please refresh the page and retry."
msgstr ""

I checked the error logs in the apache server but there are no errors reported. Would you know how to advise me to restore the situation? It happens to me on all the wordpress sites I have. I also tried temporarily disabling all plugins but it still doesn't work.

**Comment by wpdev10** [comment]
@bluenor Request to create a support request on https://userswp.io/support/ for further assistance.
