### ISSUE TITLE
Error during event demo upload

### ISSUE THREAD

**Issue by 1naveengiri** [AyeCode/userswp#764]
[24-Sep-2024 12:03:58 UTC] PHP Fatal error:  Uncaught Error: Call to a member function is_built_with_elementor() on bool in /home/rbs247/public_html/wp-content/plugins/userswp/includes/class-uwp-compatibility.php:54
Stack trace:
#0 /home/rbs247/public_html/wp-content/plugins/userswp/includes/class-uwp-compatibility.php(38): UsersWP_Compatibility::is_elementor(990546)
#1 /home/rbs247/public_html/wp-includes/class-wp-hook.php(324): UsersWP_Compatibility->users_list_item_content_elementor('', '', 990546)
#2 /home/rbs247/public_html/wp-includes/plugin.php(205): WP_Hook->apply_filters('', Array)
#3 /home/rbs247/public_html/wp-content/plugins/userswp/includes/class-templates.php(135): apply_filters('uwp_bypass_user...', '', '', 990546)
#4 /home/rbs247/public_html/wp-content/plugins/userswp/templates/bootstrap/users-item.php(10): UsersWP_Templates::users_list_item_template_content()
#5 /home/rbs247/public_html/wp-content/plugins/userswp/includes/template-functions.php(105): include('/home/rbs247/pu...')
#6 /home/rbs247/public_html/wp-content/plugins/userswp/te in /home/rbs247/public_html/wp-content/plugins/userswp/includes/class-uwp-compatibility.php on line 54

**Comment by wpdev10** [comment]
@Stiofan how about moving such compatibility functions which are used in both GD and UWP to AUI or some common class or library?
